name: Coderco secrets workflow
on: [push]

jobs:
  build:
    runs-on: ubuntu_latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: use secret
        run: echo "The secret is ${{secrets.MY_SECRET}}"
