name: Coderco secrets workflow
on: [push]

jobs:
  build:
    runs-on: ubuntu_latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: use secret
        run: echo "The secret is ${{secrets.MY_SECRET}}"

      - name: use secfret as env var
        run: echo "The seceret is $MY_SECRET"
        env:
          MY_SECRET: ${{secrets.MY_SECRET}}
