name: CoderCo Combined

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04g

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          cd chapter4
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: |
          cd chapter4
          python -m unittest discover
        if: success()

      - name: Notify success
        run: echo "Tests passed on Python ${{ matrix.python-version }}"
        if: success()
